export enum EnvVariablesEnum {
  ENVIROMENT = 'ENVIROMENT',
  VERSION = 'VERSION',
  HASH_ROUNDS = 'HASH_ROUNDS',
  TOKEN_SECRET = 'TOKEN_SECRET',
  TOKEN_EXPIRES_IN = 'TOKEN_EXPIRES_IN',
  REFRESH_SECRET = 'REFRESH_SECRET',
  REFRESH_EXPIRES_IN = 'REFRESH_EXPIRES_IN',
  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
}
