export enum OrdersUseCasesEnum {
  CREATE = 'CREATE_ORDER',
  SEARCH = 'SEARCH_ORDER',
  READ = 'READ_ORDER',
  HANDLE_ITEM = 'HANDLE_ORDER_ITEM',
  CLEAN = 'CLEAN_ORDER',
  UPDATE_STATUS = 'UPDATE_ORDER_STATUS',
  DELETE = 'DELETE_ORDER',
}
