export enum OrderStatusValuesEnum {
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
  IN_PREPARATION = 'IN_PREPARATION',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
}
